### ISSUE TITLE
Dragging to switch button does not work on iPad.

### ISSUE THREAD

**Issue by pramodchoudhari** [timmywil/jquery.onoff#1]
Good initiative to write this plugin.

We are facing issue on iPad, when try to switch button from NO state to YES state. i.e. dragging handle left to right. Handle bounce back to left or does not move at all.

However http://timmywil.github.io/jquery.onoff/ example works fine on ipad.

Would please help me out whats going wrong. 
Here Codepen : http://cdpn.io/obrna

**Comment by timmywil** [comment]
You're absolutely right. Fix incoming.

**Comment by timmywil** [comment]
Your pen seems to work now.

**Comment by pramodchoudhari** [comment]
Wow... good appreciate quick fix :)
