### ISSUE TITLE
proto.io generated html is wrong

### ISSUE THREAD

**Issue by linakis** [timmywil/jquery.onoff#4]
The generated html from http://proto.io/freebies/onoff/ is providing the following snippet:

``` html
<div class="onoffswitch">
    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch">
    <label class="onoffswitch-label" for="myonoffswitch">
        <span class="onoffswitch-inner"></span>
        <span class="onoffswitch-switch"></span>
    </label>
</div>
```

where the correct one (also mentioned in your README) is:

``` html
<div class="onoffswitch">
  <input type="checkbox" class="onoffswitch-checkbox" id="myonoffswitch" />
  <label class="onoffswitch-label" for="myonoffswitch">
    <div class="onoffswitch-inner"></div>
    <div class="onoffswitch-switch"></div>
  </label>
</div>
```

The difference is the `div` instead of `span` inside the `label` that prevented the plugin to properly figure out how to render itself.

**Comment by timmywil** [comment]
Thanks, I think proto.io actually has it right. Technically, labels can only have phrasing content as descendants (which includes `span` but not `div`). I can fix this easily enough.

**Comment by linakis** [comment]
hmm strange... I didin't spend much time on it, I just made it work and stayed there.

:+1:  for the fix
