### ISSUE TITLE
Minimal problem with the callbacks

### ISSUE THREAD

**Issue by muuvmuuv** [timmywil/jquery.onoff#7]
Hey, thanks at all for this cool thing,
my problem is followed. Every time I try to get a callback, the console gave me that issue:
Uncaught ReferenceError: $input is not defined

I did all that in the tut from Github, but doesnt work. In your example HTML-File also...
Hope you can help me as soon as possible.

Regards muuvmuuv

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a reduced test case using http://jsfiddle.net or http://jsbin.com to help assess the issue.
